### ISSUE TITLE
Link to fellowship program

### ISSUE THREAD

**Issue by felix11h** [VTeckentrup/mind-mosaic#1]
I noticed this because I also used this link before. Currently you are redirecting to the wikimedia.de page, but only the link to fellowship program on the wikiversity page 

`https://de.wikiversity.org/wiki/Wikiversity:Fellow-Programm_Freies_Wissen`

contains updated information (such as the "Aktivitäten" tab). I think the wikimedia.de site will also be taken down at some point.

**Comment by VTeckentrup** [comment]
Now I've seen the issue ;) Thanks for the heads-up, the links now point to the english wikiversity page!
